Refactor - CreditCard purchase
RoomRoster/omnipay-payrix pull request #4
Opened 2021-04-29 21:45 UTC by tszulc

2021-04-30 16:32 UTC, jorbascrumps requested changes

2021-04-30 16:32 UTC, jorbascrumps commented on src/Message/Response.php
> +            return $this->data['response']['data'][0]['status'] != static::FAILED_STATUS;
Use strict equality for comparisons.

2021-04-30 16:32 UTC, jorbascrumps commented on src/Message/AbstractRequest.php
> +     * @link https://test-portal.payrix.com/docs/api#txnsPost
```suggestion
     * @link https://portal.payrix.com/docs/api#txnsPost
```

2021-04-30 16:32 UTC, jorbascrumps commented on src/Message/PurchaseRequest.php
> +         * @link https://test-portal.payrix.com/docs/api#txnsPost
```suggestion
         * @link https://portal.payrix.com/docs/api#txnsPost
```

2021-04-30 17:17 UTC, tszulc commented on src/Message/Response.php
> +            return $this->data['response']['data'][0]['status'] != static::FAILED_STATUS;
```suggestion
            return $this->data['response']['data'][0]['status'] !== static::FAILED_STATUS;
```

2021-05-02 17:42 UTC, jorbascrumps approved these changes

2021-05-02 17:42 UTC, merged